project:
  type: book

book:
  title: "Modelos Fundacionales de IA"
  subtitle: "Modelos Fundacionales en Remote Sensing: Avances, Desafíos y Aplicaciones"
  # affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta G."
  date: "2024-12-19"
  page-footer:
    left: "Copyright 2025, Denis Berroeta"
  chapters:
    - index.qmd
    - intro.qmd
    - papers_review_vfm.qmd
    # - papers_review_vlm.qmd
    - propuesta.qmd
    # - multiagente.qmd
    # - sql.qmd
    # - rag.qmd
    # - otros_agentes.qmd
      # chapters:
      # - tarea_final.qmd
    - references.qmd

  # appendices:
    # - requerimientos.qmd
    # - glosario.qmd


#
bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denisberroeta@gmail.cl"

execute:
  warning: false

editor: source
always_allow_html: true



